### ISSUE TITLE
ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by chz** [nuxt-modules/tailwindcss#431]
### Version
@nuxtjs/tailwindcss: 5.0.0-4
nuxt: 2.15.8

### Reproduction Link
Private project. Big project

### Steps to reproduce
In a big project after hot reload many times i get FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory. 

Hot reload  time 10-11s

### What is actually happening?
After switch [v4.2.1](https://github.com/nuxt-community/tailwindcss-module/releases/tag/v4.2.1) version it works good.
Hotreload time is 1-2s

**Comment by Atinux** [comment]
Actually the v5 is made to be used with Nuxt 3

**Comment by chz** [comment]
> Actually the v5 is made to be used with Nuxt 3

Please update documentation for: Nuxt2 is not supported. Its not clear that Nuxt 2 is not supported. And its only for Nuxt 3

**Comment by aviramaz** [comment]
@Atinux / @pi0 Is it official that we won't have nuxt2+tailwind3? It's a big announcement which wasn't officially communicated till now

**Comment by Atinux** [comment]
@aviramaz have you try to follow this guide? https://tailwindcss.com/docs/guides/nuxtjs

**Comment by Rasool-deldar** [comment]
> @aviramaz have you try to follow this guide? https://tailwindcss.com/docs/guides/nuxtjs

Hi, I used tailwind 3 in Knox 3 - I installed it both through the documentation and through Knox site itself - tailwind, but unfortunately it gives me the same error.

![image](https://user-images.githubusercontent.com/58503211/155551845-1556f6aa-8414-4b94-81e4-35f1f5062fef.png)

**Comment by cossssmin** [comment]
> @aviramaz have you try to follow this guide? [tailwindcss.com/docs/guides/nuxtjs](https://tailwindcss.com/docs/guides/nuxtjs)

One issue that I've noticed is that when you're using `target: 'static'` and adding Tailwind like recommended in their docs, Nuxt 2 seems to strip out some of the CSS that relates to CSS variables that enable `ring` utilities.

For example instead of this:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/1656595/157427998-fee1de94-1a5a-415f-8e87-d3ec48421ec5.png">

<img width="565" alt="image" src="https://user-images.githubusercontent.com/1656595/157428086-e1f4e5b8-5049-4fac-8553-02dc049d9db0.png">

... you get this:

<img width="214" alt="image" src="https://user-images.githubusercontent.com/1656595/157428233-8f5fa4fd-a06e-426f-91fc-f7282ddff773.png">

![image](https://user-images.githubusercontent.com/1656595/157428453-d01acfb4-bf37-4de2-90eb-024438b2e48e.png)

As you can see, that results in `ring` utilities not working, because some CSS variable is somehow being stripped.

This is not an issue when using `target: 'server'` or when developing locally with `nuxt dev`, thus me mentioning this here first instead of opening an issue with Tailwind CSS.

**Comment by cossssmin** [comment]
☝️ Looks like the problem is that all base CSS variables that don't have a value are being stripped when doing `nuxt generate` with `target: 'static'` in nuxt.config.js

In this case, the moment I manually add `--tw-ring-inset: ;` in dev tools, it all works as expected:

![image](https://user-images.githubusercontent.com/1656595/157431193-5b0a7404-0d4c-4edd-b002-d36e7c3a5dbc.png)

**Comment by zenatshockbyte** [comment]
> @aviramaz have you try to follow this guide? https://tailwindcss.com/docs/guides/nuxtjs

Switching to this manual install seems to be way more performant (earlier we had ~7s hot reload build time, now around 1-2s) and does not cause memory issues (or at least not as quickly)

**Comment by ineshbose** [comment]
Closing this issue as it is believed to be resolved/stale now - please feel free to comment if it is still an issue in the latest version of the module.
