### ISSUE TITLE
Use with prettier-plugin-tailwindcss

### ISSUE THREAD

**Issue by awdr74100** [nuxt-modules/tailwindcss#717]
### Version
@nuxtjs/tailwindcss: v6.8.0
nuxt: v3.7.1

### Question
How does this module work with [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)? The document mentions the need to clearly indicate the location of the `tailwind.config`, but according to #660 the file appears to have been deleted. What is the location of the merged `tailwind.config`?

Thank you in advance for your help!

**Comment by ineshbose** [comment]
Hi, if your tailwind configuration is in `nuxt.config`, you should move it out to a separate config file since Tailwind v3.3 can read ESM/TS configurations. If you do not wish to do so, you can also write a custom module and then configure the plugin to read that file as written in the docs. https://tailwindcss.nuxtjs.org/tailwind/editor-support
