### ISSUE TITLE
Ditch logging viewer URL in favour of devtools

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-modules/tailwindcss#798]
### Is your feature request related to a problem? Please describe.

When users are using DevTools the expected workflow for viewing tailwind debug should be via the DevTools tab, not a separate link.

![image](https://github.com/nuxt-modules/tailwindcss/assets/5326365/e26cbb45-e7ac-4ad6-842c-dda2d38c33ce)

I'd also like to see the "Using default Tailwind CSS file" removed but may need some discussion.

![image](https://github.com/nuxt-modules/tailwindcss/assets/5326365/c9664269-61d5-476a-9e38-08ba7cb7d3d6)

### Describe the solution you'd like

For the log line to be disabled if DevTools is enabled.

**Comment by ineshbose** [comment]
I like this. The path still remains exposed despite not console logging it, correct? because devtools uses iframe for it. However, nuxt2 won't be able to take advantage of this, so the link still needs to be logged there. I'll make this part of v7 (#790). Meanwhile if you want to disable logging, you can use `quiet: true` for module config.

**Comment by ineshbose** [comment]
Released in nightly!
