### ISSUE TITLE
Using `c12` and adding support for `/.config`

### ISSUE THREAD

**Issue by zoey-kaiser** [nuxt-modules/tailwindcss#808]
### Is your feature request related to a problem? Please describe.

Words directly take from @pi0, as I think he states the problem perfectly:

> Due to a lack of standards for where tools store their configuration, the number of top-level configuration files in projects is increasing day by day. See [.config dir proposal](https://github.com/pi0/config-dir) for more context.

### Describe the solution you'd like
I propose supporting `.config/tailwind.config.js` and `.config/tailwind.js` as alternative places to check and load the tailwind configuration if top-level tailwind.config.ts does not exist to unblock adopting this new convention across the ecosystem.

In Nuxt/CLI Version 3.10.1 (or more specifically `c12`, the config loader) this was now added. https://github.com/nuxt/cli/releases/tag/v3.10.1. You can therefore now store your `nuxt.config.ts` inside `./config/nuxt.config.ts`. 

### Describe alternatives you've considered
Just the root folder.

**Comment by ineshbose** [comment]
Thanks for opening this issue - completely up to adding this!

I believe this may need the module to make use of `c12` - which it doesn't yet - and I'm thinking about how this may work with `configPath` module option..

**Comment by pi0** [comment]
Thanks for raising issue @zoey-kaiser.

I let the implementation details to @ineshbose on how to move it forward. Both migration to c12 or using configPath to check two alternative places looks good to me 👍🏼 

AFAIK, the reason that Nuxt tailwind module supports external `tailwind.config` file, is IDE support for tailwind extension that picks the particular file (otherwise most of the times we prefer to use inline config inside `nuxt.config`/`.config/nuxt`.

I think it would be nice idea to have our module prepared for this change and at the same time also raise on in [tailwindcss](https://github.com/tailwindlabs/tailwindcss) repo to ask considering it as a core feature. We might also raise another in [tailwindcss-intellisense](https://github.com/tailwindlabs/tailwindcss-intellisense) to support alternative path matching tailwind core.

**Comment by zoey-kaiser** [comment]
Amazing! Thank you to both of you! I love that this new method of handling configs is starting to be adopted in the Nuxt Ecosystem, as I feel like it is a big pain point for developers, that we kind of accepted, without every thinking of better alternatives. 

If I can contribute in any way, please let me know! I would update all the sidebase modules to support this, however we do not use any kind of config files, aside from the Nuxt config!

**Comment by pi0** [comment]
Thanks for research @zoey-kaiser. Do you mind to make an issue to followup this also in tailwindcss? While they allow a custom method to define config, if we want to get rid of top level configs (for real) we need to probably extend CONFIG_GLOB and intellisense that works out of the box.

**Comment by zoey-kaiser** [comment]
> Thanks for research @zoey-kaiser. Do you mind to make an issue to followup this also in tailwindcss? While they allow a custom method to define config, if we want to get rid of top level configs (for real) we need to probably extend CONFIG_GLOB and intellisense that works out of the box.

Yes, of course! Ill link back both issues, once they are opened.

**Comment by ineshbose** [comment]
OK - I have been brainstorming on this for quite a while now. Aiming to land this in v6.13.0 where we see a little rewrite on loading config strategy (this is important as we heavily rely on `tailwindcss/loadConfig`, but I am looking to provide an experimental option to support Tailwind v4 in v6 of this module and that could break many things). I realise that the layer loading strategy is also quite flawed where a layer's `tailwindcss` options in `nuxt.config` aren't considered and also `configPaths` overrides the layer's `tailwind.config`.

In addition, I really want to also include #842 so that IntelliSense or any HMR can work without any extra configuration. Hopefully these will give a great base for additional features in (potentially) the final minor for v6.

**Comment by ineshbose** [comment]
Merged! Could you give `nightly` a try and let me know how it goes please?

https://tailwindcss.nuxtjs.org/getting-started/installation#opting-into-the-nightly-channel

**Comment by ineshbose** [comment]
If you get the chance to try the change and provide feedback that everything is stable, let me know 🙂 

Happy holidays!
