### ISSUE TITLE
Tailwindcss added at last is not applied

### ISSUE THREAD

**Issue by bippan1407** [nuxt-modules/tailwindcss#854]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.1`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `yarn@4.2.2`
- Builder:          `-`
- User Config:      `devtools`, `debug`, `hooks`, `modules`, `plugins`, `nitro`, `runtimeConfig`, `dayjs`, `postcss`, `app`, `css`, `apollo`, `carousel`, `tour`, `vue`, `routeRules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.12.0`, `@nuxtjs/device@3.1.1`, `@nuxt/image@1.4.0`, `@pinia/nuxt@0.5.1`, `@pinia-plugin-persistedstate/nuxt@1.2.0`, `dayjs-nuxt@2.1.9`, `vue3-carousel-nuxt@1.1.1`, `@nuxtjs/apollo@5.0.0-alpha.14`, `nuxt-tour@0.0.9`, `@nuxtjs/i18n@8.3.1`
- Build Modules:    `-`

### Reproduction

Cannot reproduce the issue either on new repo or stackblitz

### Describe the bug

In the below image in nuxt 3 bg-transparent is added at last but it is overridden by bg-yocket-neutral-100

<img width="647" alt="Screenshot 2024-05-28 at 5 46 06 PM" src="https://github.com/nuxt/nuxt/assets/45727492/081685a9-7c97-4f4e-8449-e3f0bfbc0719">

In nuxt 2 the behaviour was opposite
<img width="1115" alt="Screenshot 2024-05-28 at 5 52 22 PM" src="https://github.com/nuxt/nuxt/assets/45727492/f4d6d5f5-d323-4312-bb37-46a4fb52f776">

This same thing is happening throughout the project

**Comment by ineshbose** [comment]
OK - I've researched about your issue and am able to report back my findings!

Let's note couple of observations here -
1. We have a child component that has `bg-yocket-neutral-100` by default, but the parent can provide additional classes (due to Vue fallthrough attributes); in this case we provide `bg-transparent`.
2. Classes appearing later in the DOM take precedence, i.e. `bg-transparent` should override `bg-yocket-neutral-100` (both have same specificity).
3. Minor thing I noted, the styles are inlined to the head in the Nuxt 2 app, while external in Nuxt 3 (configurable, but this behaviour is likely better).
4. Tailwind may add `bg-yocket-neutral-100` and `bg-transparent` in different orders to the bundled CSS based on content detection, but the order of declaration in your styles does not quite affect the preference.

It's an odd problem, and thanks for reporting - but it seems to be out of scope of Nuxt and Tailwind CSS both; it's more of a HTML/CSS issue, and that's what Tailwind seeks to solve with its principles (when followed well). We would need to look into how Tailwind is being configured, how it scans our source files for content detection and see the generated CSS which isn't worth much. Going over what readings I did for this - [CSS preference](https://stackoverflow.com/a/3671560/12938670), [Vue Fallthrough Attributes / `class` merging](https://vuejs.org/guide/components/attrs#class-and-style-merging), https://github.com/tailwindlabs/tailwindcss/issues/1452, and [another related StackOverflow question](https://stackoverflow.com/questions/72148525/tailwindcss-3-classes-doesnt-override-previous-classes), it seems that we're looking to improve the component design here of the child for better usage with the parent using [tailwind-merge](https://github.com/dcastil/tailwind-merge).

Based on your demo, this is how I'll refactor the Child component:
```html
<script setup>
import { twMerge } from 'tailwind-merge'
</script>

<template>
  <div :class="twMerge('bg-slate-700 w-20 h-20 border-8 border border-red-800', $attrs.class)">TEST</div>
</template>
```

While this may not be perfect Tailwind usage (i.e., we still have `bg-slate-700` defaulted), this should eliminate the conflicting classes for your component and hopefully be easier for your DOM too. Let me know!

**Comment by bippan1407** [comment]
Thanks @ineshbose for the detailed answer.

I guess tailwind-merge will be my last option.

**Comment by bippan1407** [comment]
There is another tailwind css issue similar to current issuer related to CSS specificity, css does not remain consistent when dev server is restarted. 

I have recorded the issue.

https://drive.google.com/file/d/1HJ7y2opGSoUkSgCzK8qnnvyvtcPbE2ig/view?usp=drive_link


Github link for code - https://github.com/bippan1407/nuxt-explore/tree/tailwind-issue

CSS specificity while working on dev and after restarting the dev should remain same. @ineshbose

**Comment by ineshbose** [comment]
Thanks for providing a repo. Few things - the content configuration isn't required (Child.vue should definitely be in a components directory), and would the PostCSS and module configurations be necessary (the defaults may be sensible), though I'm sure you have your reasons.

> There is another tailwind css issue similar to current issue related to CSS specificity, css does not remain consistent when dev server is restarted.

The CSS specificity remains the same for your classes - `(0,1,0)`; it's just the HMR that may be triggering content detection JIT to give one class preference over other, but it's still conflicting classes and relying on class order isn't ideal.

> I guess tailwind-merge will be my last option.

I would understand if it's not motivating enough to add in a library to your project, but I think this would be a good addition, and it shouldn't be the last option (but rather the first 🙂). As I mention above, Nuxt provides you a framework to develop fullstack apps using Vue, while Tailwind CSS provides declarative utilities to create UI, but the usage of these tools with their principles is fundamental. [As Adam Wathan says that specificity conflict merging is outside Tailwind's scope](https://github.com/tailwindlabs/tailwindcss/discussions/1446#discussioncomment-56769), that's why projects like tailwind-merge exist and it's used in libraries like [Nuxt UI](https://github.com/nuxt/ui) where developers are provided the ability to pass any additional Tailwind utilities into the components that get merged with the defaults. You could say that this comes down to component-design preference, that if you want your components to be dumb/state-less and not have a default bg, or you want them to be smart and then also be able to remove conflicting classes when passed on the client level.

Why this wasn't an issue for you in Nuxt 2 is odd - it may be due to the inline styles and Webpack 4 loaders, but if you move that over to an external stylesheet and Webpack5/Vite, it's possible that the same issue would persist because your project would be relying on the order of conflicting classes still, so in such case, we design our components to be safer and more reliable. Let me know what you think. 🙂

**Comment by ineshbose** [comment]
I'll close this issue, as it is out of scope, but feel free to continue discussion..

**Comment by bippan1407** [comment]
Thank's for the answer @ineshbose
